LOGDIR="/cache/arch-chroot"
# LOGDIR="/var/log/arch-chroot"
POOL=(
    "/var/chroot"
    "/etc/arch-chroot/chroot"
#    "/data/adb/modules/arch-chroot/system/etc/arch-chroot/chroot"
)
INIT="/init"
# INIT="/bin/init"
# INIT="/usr/local/bin/init"
HALT="/usr/local/bin/halt"
